# Base configs
baseurl: "FrancisGarrity.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: 
subtitle: 
author: 
header:
 title: 
 subtitle: 
footer:
 name: 
 bio: 
 github: 
web_design: "AJ"
social_urls:
  facebook: 
  twitter: 
  instagram: 
  dribbble: 
  linkedin: 
  github: 
